services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0

  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/clinica
      - ENCRYPT_KEY=claveSecreta123456
